using calumet;
using calumet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;

namespace calumet.Controllers
{
    public class EventController : BaseController
    {
        public IEnumerable<Event> GetAllEvents()
        {
            using (var db = dbio.db)
            {
                var events =  db.Events.ToArray();
                return events;
            }
        }

        public HttpResponseMessage PostEvent(Event ev)
        {
            if(ev == null)
            {
                throw new ArgumentNullException();
            }
            using (var db = dbio.db)
            {
                //I have to save it twice; once to get the autogenerated ID and the other to save the event link
                // SUPER INEFFICIENT but fast is good for this type of project
                db.Events.Add(ev);
                db.SaveChanges();
                ev.EventLink = "/events.html?id=" + ev.EventID;
                db.SaveChanges();
            }
            var response = Request.CreateResponse(HttpStatusCode.Created, ev);
            //string uri = Url.Link("MajorAPI", new { id = ev.EventID });
            //response.Headers.Location = new Uri(uri);
            return response;
        }
        
    }
}